### ISSUE TITLE
Endpoint(s) to invalidate a specific cache on demand

### ISSUE THREAD

**Issue by colacadstink** [wdwnt/fastpass#14]
It would be incredibly useful to invalidate a cached value on demand. Situations like the one that came up during the live show, where we needed to embed a video quickly but FastPass wasn't being... uh... fast, raise a need for us to be able to force a cached value to be trashed immediately. 

It might be nice to have this for many endpoints (possibly all endpoints?), in case a similar need exists elsewhere in the future; perhaps make one endpoint that takes the cache to invalidate as a parameter?

**Comment by mvbattista** [comment]
resolved by https://github.com/wdwnt/fastpass/commit/820f41faa828e0964116f5f032af7693a3ab43d2
