### ISSUE TITLE
App Notification Fastpass Endpoint

### ISSUE THREAD

**Issue by daddy1243** [wdwnt/fastpass#17]
We need an endpoint to cache/process the new app notification endpoint.
The WP link is here: https://wdwnt.com/wp-json/wp/v2/app_notification?page=1&per_page=8

The output should be a JSON with the following format:

    {
	"id": 153150,
	"date": "2019-04-19T10:55:10",
	"type": "app_notification",
	"title":  "[Test] Happy Birthday!",
	"text": "<p>Happy Birthday, Jason!<\/p>\n",
	"app_notification_category": [9708],
	"app_notification_type": [9709],
    }

**Comment by Kpudlo** [comment]
The WP link for the live site is here: https://wdwnt.com/wp-json/wp/v2/app_notification?page=1&per_page=8. The other link provided is for the test environment

**Comment by mvbattista** [comment]
Following standard practice returning the date in GMT as opposed to requested local.
