### ISSUE TITLE
Add a way to invalidate/refresh cache for a specific URL

### ISSUE THREAD

**Issue by colacadstink** [wdwnt/fastpass#27]
Provide some mechanism to invalidate a cached value on demand. The initial use case for this is when a blog post is updated, someone would poke this endpoint for that matching blog post, invalidating or refreshing (your choice, no preference here) the cached value. Currently, it remains valid for up to 5 minutes, which can lead to some confusion when reading articles on the app.

**Comment by mvbattista** [comment]
Resolved by 431d359fa4f2b6180cdfffc17a9c74c1223990a2
